version: "3.1"

services:
  db:
    image: mysql:9.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "realworld_dev"
      MYSQL_USER: "realworld"
      MYSQL_PASSWORD: "realworld"
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
