// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "github.com/jeanpsv/realworld-golang/models"
	mock "github.com/stretchr/testify/mock"
)

// TagUseCase is an autogenerated mock type for the TagUseCase type
type TagUseCase struct {
	mock.Mock
}

// List provides a mock function with no fields
func (_m *TagUseCase) List() ([]*models.Tag, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Tag, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Tag); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTagUseCase creates a new instance of TagUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagUseCase {
	mock := &TagUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
