name: Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
          with:
            go-version: "1.23"
      - name: Test
        run: go test -v ./...
